FROM python:3.12-slim
COPY wheelhouse_linux_build /wheelhouse
RUN pip install --no-index --find-links /wheelhouse deepeval && rm -rf /wheelhouse && pip install -q httpx -i https://pypi.tuna.tsinghua.edu.cn/simple
CMD ["python"]
